<a href="https://colab.research.google.com/github/nivedhitha-e/240901070-PYTHON/blob/main/240901070_Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("Original arrays")
print(a)
print(b)
print("\nVector addition")
print(a+b)
print("\nVector Subtraction")
print(a-b)
print("\nVector Multiplication")
print(a*b)
print("\nVector Division")
print(a/b)
print("\nVector Dot product")
print(a.dot(b))
print("\nScalar multiplication")
sclr=5
print("Scalar value=",sclr)

Original arrays
[10 20 30 40 50]
[ 2  4  5  8 10]

Vector addition
[12 24 35 48 60]

Vector Subtraction
[ 8 16 25 32 40]

Vector Multiplication
[ 20  80 150 320 500]

Vector Division
[5. 5. 6. 5. 5.]

Vector Dot product
1070

Scalar multiplication
Scalar value= 5
