<a href="https://colab.research.google.com/github/nivedhitha-e/240901070-PYTHON/blob/main/240901070_Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#index retrival
import numpy as np
arr=np.array([1,2,3,4,5,6,4])
print(arr)
x=np.where(arr==4)
print(x)


[1 2 3 4 5 6 4]
(array([3, 6]),)


In [2]:
#Indices where the values are even
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7]),)


In [14]:
#Sorting the array
arr=np.array([3,2,0,1])
print("\nOriginal arrray:\n",arr)
print("\nSorted array:\n",np.sort(arr))
arr=np.array([[3,2,4],[5,0,1]])
print("\nOriginal array:\n",arr)
print("\nSorted array:\n",np.sort(arr))


Original arrray:
 [3 2 0 1]

Sorted array:
 [0 1 2 3]

Original array:
 [[3 2 4]
 [5 0 1]]

Sorted array:
 [[2 3 4]
 [0 1 5]]


In [6]:
import numpy as np
sorted_array=np.array([1,3,5,7])
values=[2,4,6]
insert_indices=np.searchsorted(sorted_array,values)
print(sorted_array)
print(values)
print(insert_indices)

[1 3 5 7]
[2, 4, 6]
[1 2 3]


In [8]:
#Filtering1
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("\nFilter array:",newarr)


Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]


In [18]:
#Filtering2
arr=np.array([41,42,43,44])
filter_arr=arr>42
newarr=arr[filter_arr]
print("Original array:\n",arr)
print("Filter array:condition->42:\n",filter_arr)
print("Filter array:\n",newarr)

Original array:
 [41 42 43 44]
Filter array:condition->42:
 [False False  True  True]
Filter array:
 [43 44]
