<a href="https://colab.research.google.com/github/nivedhitha-e/240901070-PYTHON/blob/main/240901070%20Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print("Original array:\n",arr)

Original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [ ]:
#returns every other rows
print("\nEvery other rows:\n",arr[0:3:2])


Every other rows:
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [ ]:
#returns every other element from the entire array
arr=np.array([1,2,3,4,5,6,7])
print("\nOriginal array:\n",arr)
print("\nReturns every other elements in the array arr[::2]:\n",arr[::2])


Original array:
 [1 2 3 4 5 6 7]

Returns every other elements in the array arr[::2]:
 [1 3 5 7]


In [ ]:
#Slicing array
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
temp=arr[:2,:3]
print("\nArray with first 2 rows and 3 columns:\n",temp)


Array with first 2 rows and 3 columns:
 [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [ ]:
#Interger array indexing
temp1=arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices (0,3),(1,2),(2,1),(3,0):\n",temp1)


Elements at indices (0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]


In [ ]:
#Boolean array indexing
cond=arr>2
#cond is a boolean array
temp2=arr[cond]
print("\nElements greater than 2:\n",temp2)


Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]
