<a href="https://colab.research.google.com/github/nivedhitha-e/240901070-PYTHON/blob/main/240901070_SKILL_TEST_3(B).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Question 3(B): Perform Matrix Manipulation on Stock Price Data
Problem Statement:
A stock analyst is analyzing two stocks using their daily price data recorded over a week.
Each stock's data is represented as a 5x3 matrix, where:
● Each row represents a day (5 days in total).
● Each column represents a different price feature: Open, High, and Low.
Write a Python program to:
● Compute the element-wise sum of the two matrices to analyze combined price
values.
● Compute the element-wise difference to understand the daily spread between the
two stocks.
Use NumPy for matrix operations.

In [3]:
import numpy as np
# Stock A price data (5 days × 3 features: Open, High, Low)
stock_A = np.array([
[100, 105, 98],
[102, 108, 101],
[104, 110, 103],
[103, 107, 100],
[105, 112, 104]
])
# Stock B price data (5 days × 3 features: Open, High, Low)
stock_B = np.array([
[98, 103, 95],
[101, 106, 99],
[102, 109, 100],
[100, 104, 97],
[103, 108, 101]
])
print("Stock A Data:\n", stock_A)
print("\nStock B Data:\n", stock_B)
# Element-wise sum
sum_matrix = stock_A + stock_B
print("\nElement-wise Sum of Stock Prices:\n", sum_matrix)
# Element-wise difference
difference_matrix = stock_A - stock_B
print("\nElement-wise Difference of Stock Prices:\n", difference_matrix)

Stock A Data:
 [[100 105  98]
 [102 108 101]
 [104 110 103]
 [103 107 100]
 [105 112 104]]

Stock B Data:
 [[ 98 103  95]
 [101 106  99]
 [102 109 100]
 [100 104  97]
 [103 108 101]]

Element-wise Sum of Stock Prices:
 [[198 208 193]
 [203 214 200]
 [206 219 203]
 [203 211 197]
 [208 220 205]]

Element-wise Difference of Stock Prices:
 [[2 2 3]
 [1 2 2]
 [2 1 3]
 [3 3 3]
 [2 4 3]]
