<a href="https://colab.research.google.com/github/nivedhitha-e/240901070-PYTHON/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array creaeted:\n",a)

Array creaeted:
 [[1 2 4]
 [5 8 7]]


In [ ]:
#Creating a 3x4 array with all zeros
b=np.zeros((3,4))
print("Array with all zeros:\n",b)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Creating a costant value array
c=np.full((3,3),6)
print("Array with all 6s:\n",c)

Array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
#Create an array wit random value
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.0067764  0.70604821]
 [0.20876702 0.66952414]]


In [ ]:
#Create a sequence of intergers from 0 to 30 with step of 5
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [ ]:
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\nOriginal array:\n",arr)
print("Reshaped array [4,3]:\n",newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array [4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [ ]:
#Flatten array
flarr=arr.flatten()
print("\nOriginal array:\n",arr)
print("\nFlattened arrayL\n",flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

Flattened arrayL
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [ ]:
print("\nNo. of dimensions:\n",arr.ndim)
print("\nShape of array:\n",arr.shape)
print("\nSize of array:\n",arr.size)
print("\nArray type:\n",arr.dtype)
newtype=arr.astype('f')
print("\nConverted array element:\n",newtype)
print("\nConverted array type:\n",newtype.dtype)


No. of dimensions:
 2

Shape of array:
 (3, 4)

Size of array:
 12

Array type:
 int64

Converted array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

Converted array type:
 float32


In [ ]:
#Slicing
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])
print(p[2,0:2])
print(p[2:,2:])
print(p[3:,3:])
print(p[:,1])
c=p.astype('f')
print(c)

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[7 8]
[[ 9]
 [12]
 [15]]
[]
[ 2  5  8 11 14]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
